version: "2"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
    volumes:
      - /var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
  slave1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: otomato/jenkins-slave:0.8
